# TCL File Generated by Component Editor 15.1
# Tue Apr 05 23:17:29 CEST 2016
# DO NOT MODIFY


# 
# lcd_avalon_dma "lcd_avalon_dma" v1.0
#  2016.04.05.23:17:29
# lcd ctrl with DMA capability
# 

# 
# request TCL package from ACDS 15.1
# 
package require -exact qsys 15.1


# 
# module lcd_avalon_dma
# 
set_module_property DESCRIPTION "lcd ctrl with DMA capability"
set_module_property NAME lcd_avalon_dma
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME lcd_avalon_dma
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL lcd_dma
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file dma_controller_behavior.vhdl VHDL PATH dma_controller_behavior.vhdl
add_fileset_file dma_controller_entity.vhdl VHDL PATH dma_controller_entity.vhdl
add_fileset_file lcd_dma_behavior.vhdl VHDL PATH lcd_dma_behavior.vhdl
add_fileset_file lcd_dma_entity.vhdl VHDL PATH lcd_dma_entity.vhdl TOP_LEVEL_FILE
add_fileset_file pixel_formatter_behavior.vhdl VHDL PATH pixel_formatter_behavior.vhdl
add_fileset_file pixel_formatter_entity.vhdl VHDL PATH pixel_formatter_entity.vhdl
add_fileset_file send_receive_if_behavior.vhdl VHDL PATH send_receive_if_behavior.vhdl
add_fileset_file send_receive_if_entity.vhdl VHDL PATH send_receive_if_entity.vhdl


# 
# parameters
# 


# 
# display items
# 


# 
# connection point LCD_conduit
# 
add_interface LCD_conduit conduit end
set_interface_property LCD_conduit associatedClock ""
set_interface_property LCD_conduit associatedReset ""
set_interface_property LCD_conduit ENABLED true
set_interface_property LCD_conduit EXPORT_OF ""
set_interface_property LCD_conduit PORT_NAME_MAP ""
set_interface_property LCD_conduit CMSIS_SVD_VARIABLES ""
set_interface_property LCD_conduit SVD_ADDRESS_GROUP ""

add_interface_port LCD_conduit ChipSelectBar lcd_cs Output 1
add_interface_port LCD_conduit DataBus lcd_data Bidir 16
add_interface_port LCD_conduit DataCommandBar lcd_dc Output 1
add_interface_port LCD_conduit IM0 lcd_im Output 1
add_interface_port LCD_conduit ReadBar lcd_rd Output 1
add_interface_port LCD_conduit ResetBar lcd_rst Output 1
add_interface_port LCD_conduit WriteBar lcd_we Output 1


# 
# connection point irq
# 
add_interface irq interrupt end
set_interface_property irq associatedAddressablePoint avalon_slave
set_interface_property irq associatedClock clock_sink
set_interface_property irq associatedReset reset_sink
set_interface_property irq bridgedReceiverOffset ""
set_interface_property irq bridgesToReceiver ""
set_interface_property irq ENABLED true
set_interface_property irq EXPORT_OF ""
set_interface_property irq PORT_NAME_MAP ""
set_interface_property irq CMSIS_SVD_VARIABLES ""
set_interface_property irq SVD_ADDRESS_GROUP ""

add_interface_port irq end_of_transaction_irq irq Output 1


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0
set_interface_property clock_sink ENABLED true
set_interface_property clock_sink EXPORT_OF ""
set_interface_property clock_sink PORT_NAME_MAP ""
set_interface_property clock_sink CMSIS_SVD_VARIABLES ""
set_interface_property clock_sink SVD_ADDRESS_GROUP ""

add_interface_port clock_sink Clock clk Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock ""
set_interface_property reset_sink synchronousEdges NONE
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink Reset reset Input 1


# 
# connection point avalon_master
# 
add_interface avalon_master avalon start
set_interface_property avalon_master addressUnits SYMBOLS
set_interface_property avalon_master associatedClock clock_sink
set_interface_property avalon_master associatedReset reset_sink
set_interface_property avalon_master bitsPerSymbol 8
set_interface_property avalon_master burstOnBurstBoundariesOnly false
set_interface_property avalon_master burstcountUnits WORDS
set_interface_property avalon_master doStreamReads false
set_interface_property avalon_master doStreamWrites false
set_interface_property avalon_master holdTime 0
set_interface_property avalon_master linewrapBursts false
set_interface_property avalon_master maximumPendingReadTransactions 0
set_interface_property avalon_master maximumPendingWriteTransactions 0
set_interface_property avalon_master readLatency 0
set_interface_property avalon_master readWaitTime 1
set_interface_property avalon_master setupTime 0
set_interface_property avalon_master timingUnits Cycles
set_interface_property avalon_master writeWaitTime 0
set_interface_property avalon_master ENABLED true
set_interface_property avalon_master EXPORT_OF ""
set_interface_property avalon_master PORT_NAME_MAP ""
set_interface_property avalon_master CMSIS_SVD_VARIABLES ""
set_interface_property avalon_master SVD_ADDRESS_GROUP ""

add_interface_port avalon_master master_address address Output 32
add_interface_port avalon_master master_burst_count burstcount Output 8
add_interface_port avalon_master master_read read Output 1
add_interface_port avalon_master master_read_data readdata Input 32
add_interface_port avalon_master master_read_data_valid readdatavalid Input 1
add_interface_port avalon_master master_wait_request waitrequest Input 1


# 
# connection point avalon_slave
# 
add_interface avalon_slave avalon end
set_interface_property avalon_slave addressUnits WORDS
set_interface_property avalon_slave associatedClock clock_sink
set_interface_property avalon_slave associatedReset reset_sink
set_interface_property avalon_slave bitsPerSymbol 8
set_interface_property avalon_slave burstOnBurstBoundariesOnly false
set_interface_property avalon_slave burstcountUnits WORDS
set_interface_property avalon_slave explicitAddressSpan 0
set_interface_property avalon_slave holdTime 0
set_interface_property avalon_slave linewrapBursts false
set_interface_property avalon_slave maximumPendingReadTransactions 0
set_interface_property avalon_slave maximumPendingWriteTransactions 0
set_interface_property avalon_slave readLatency 0
set_interface_property avalon_slave readWaitTime 1
set_interface_property avalon_slave setupTime 0
set_interface_property avalon_slave timingUnits Cycles
set_interface_property avalon_slave writeWaitTime 0
set_interface_property avalon_slave ENABLED true
set_interface_property avalon_slave EXPORT_OF ""
set_interface_property avalon_slave PORT_NAME_MAP ""
set_interface_property avalon_slave CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave slave_cs chipselect Input 1
add_interface_port avalon_slave slave_we write Input 1
add_interface_port avalon_slave slave_rd read Input 1
add_interface_port avalon_slave slave_write_data writedata Input 32
add_interface_port avalon_slave slave_read_data readdata Output 32
add_interface_port avalon_slave slave_wait_request waitrequest Output 1
add_interface_port avalon_slave slave_address address Input 3
set_interface_assignment avalon_slave embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave embeddedsw.configuration.isPrintableDevice 0

