# TCL File Generated by Component Editor 15.1
# Tue Apr 05 16:33:49 CEST 2016
# DO NOT MODIFY


# 
# lcd_avalon_slave "lcd_avalon_slave" v1.0
#  2016.04.05.16:33:49
# LCD ctrl for an Avalon Slave interface
# 

# 
# request TCL package from ACDS 15.1
# 
package require -exact qsys 15.1


# 
# module lcd_avalon_slave
# 
set_module_property DESCRIPTION "LCD ctrl for an Avalon Slave interface"
set_module_property NAME lcd_avalon_slave
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME lcd_avalon_slave
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL lcd_avalon_slave
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file lcd_avalon_slave_behavior.vhdl VHDL PATH lcd_avalon_slave_behavior.vhdl
add_fileset_file lcd_avalon_slave_entity.vhdl VHDL PATH lcd_avalon_slave_entity.vhdl TOP_LEVEL_FILE
add_fileset_file send_receive_if_behavior.vhdl VHDL PATH send_receive_if_behavior.vhdl
add_fileset_file send_receive_if_entity.vhdl VHDL PATH send_receive_if_entity.vhdl


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0
set_interface_property clock_sink ENABLED true
set_interface_property clock_sink EXPORT_OF ""
set_interface_property clock_sink PORT_NAME_MAP ""
set_interface_property clock_sink CMSIS_SVD_VARIABLES ""
set_interface_property clock_sink SVD_ADDRESS_GROUP ""

add_interface_port clock_sink Clk50_CI clk Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock_sink
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink Reset_RI reset Input 1


# 
# connection point LCD_conduit
# 
add_interface LCD_conduit conduit end
set_interface_property LCD_conduit associatedClock ""
set_interface_property LCD_conduit associatedReset ""
set_interface_property LCD_conduit ENABLED true
set_interface_property LCD_conduit EXPORT_OF ""
set_interface_property LCD_conduit PORT_NAME_MAP ""
set_interface_property LCD_conduit CMSIS_SVD_VARIABLES ""
set_interface_property LCD_conduit SVD_ADDRESS_GROUP ""

add_interface_port LCD_conduit LCD_cs_SBO lcd_cs Output 1
add_interface_port LCD_conduit LCD_data_IO lcd_data Bidir 16
add_interface_port LCD_conduit LCD_DaCmd_SBO lcd_dc Output 1
add_interface_port LCD_conduit LCD_IM0_SO  lcd_im Output 1
add_interface_port LCD_conduit LCD_rd_SBO lcd_de Output 1
add_interface_port LCD_conduit LCD_Reset_RBO lcd_rst Output 1
add_interface_port LCD_conduit LCD_we_SBO lcd_we Output 1


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock_sink
set_interface_property avalon_slave_0 associatedReset reset_sink
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 maximumPendingWriteTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0
set_interface_property avalon_slave_0 ENABLED true
set_interface_property avalon_slave_0 EXPORT_OF ""
set_interface_property avalon_slave_0 PORT_NAME_MAP ""
set_interface_property avalon_slave_0 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0 AVSlave_cs_SI chipselect Input 1
add_interface_port avalon_slave_0 AVSlave_we_SI write Input 1
add_interface_port avalon_slave_0 AVSlave_rd_SI read Input 1
add_interface_port avalon_slave_0 AVSlave_we_DI writedata Input 32
add_interface_port avalon_slave_0 AVSlave_rd_DO readdata Output 32
add_interface_port avalon_slave_0 AVSlave_wtReq_SO waitrequest Output 1
add_interface_port avalon_slave_0 AVSlave_addr_DI address Input 2
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0

